server:
  port: 8085
spring:
  thymeleaf:
    cache: false
#mysql_setting
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rain?serverTimezone=Asia/Seoul
    username: yjyj0345
    password: a1234
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
#mybatis
mybatis:
  type-aliases-package: thyme.data.dto
  mapper-locations:
  - /mapper/**/*.xml

