server:
  port: 9002
#mysql setting
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rain?serverTimezone=Asia/Seoul
    username: yjyj0345
    password: a1234
#jsp settings
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  devtools:
    livereload:
      enabled: true
#mybatis
mybatis:
  type-aliases-package: boot.data.dto
  mapper-locations:
  - /mapper/**/*.xml